# Generated by Django 3.0.3 on 2020-04-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Going',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(help_text='Enter the type of track', max_length=50)),
                ('condition', models.CharField(help_text='Enter the condition', max_length=50)),
                ('chinese_condition', models.CharField(blank=True, help_text='Enter the chinese condition', max_length=50)),
                ('code', models.CharField(help_text='Enter the condition code', max_length=5)),
            ],
            options={
                'ordering': ['track'],
            },
        ),
        migrations.CreateModel(
            name='RacingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Enter the place of track', max_length=50)),
                ('chinese_place', models.CharField(blank=True, help_text='Enter the Chinese place name of the track', max_length=50)),
                ('course', models.CharField(blank=True, help_text='Enter the course of the track', max_length=5)),
                ('home_straight_M', models.PositiveIntegerField(blank=True, help_text='Enter the condition code')),
                ('width_M', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
            options={
                'ordering': ['course'],
            },
        ),
    ]
