# Generated by Django 3.0.3 on 2020-04-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Going',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(help_text='Enter the type of track', max_length=50)),
                ('condition', models.CharField(help_text='Enter the condition', max_length=50)),
                ('chinese_condition', models.CharField(blank=True, help_text='Enter the chinese condition', max_length=50)),
                ('code', models.CharField(help_text='Enter the condition code', max_length=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['track'],
            },
        ),
        migrations.CreateModel(
            name='Jockey_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the jockey's name", max_length=50)),
                ('chinese_name', models.CharField(blank=True, help_text="Enter the jockey's chinese name", max_length=50)),
                ('hkjc_id', models.CharField(help_text="Enter the jockey's hkjc id", max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RacingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Enter the place of track', max_length=50)),
                ('chinese_place', models.CharField(blank=True, help_text='Enter the Chinese place name of the track', max_length=50)),
                ('course', models.CharField(blank=True, help_text='Enter the course of the track', max_length=5)),
                ('home_straight_M', models.FloatField(help_text='Enter the Home Straight(M)')),
                ('width_M', models.FloatField(help_text='Enter the Width(M)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Trainer_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the Trainer's name", max_length=50)),
                ('chinese_name', models.CharField(blank=True, help_text="Enter the Trainer's chinese name", max_length=50)),
                ('hkjc_id', models.CharField(help_text="Enter the jockey's hkjc id", max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakes_won', models.FloatField(help_text='Enter the stakes Stakes won')),
                ('wins_past_10_racing', models.PositiveSmallIntegerField(help_text='Enter the No. of Wins in past 10 race days')),
                ('number_win', models.IntegerField(help_text='No. of Wins')),
                ('number_second', models.IntegerField(help_text='No. of 2nds')),
                ('number_third', models.IntegerField(help_text='No. of 3rds')),
                ('number_fourth', models.IntegerField(help_text='No. of 4ths')),
                ('total_runners', models.IntegerField(help_text='Total Runners')),
                ('win_rate', models.FloatField(help_text='Win %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trainer_Info', to='HKJC_database.Trainer_Info')),
            ],
            options={
                'ordering': ['number_win'],
            },
        ),
        migrations.CreateModel(
            name='Jockey_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakes_won', models.FloatField(help_text='Enter the stakes Stakes won')),
                ('wins_past_10_racing', models.PositiveSmallIntegerField(help_text='Enter the No. of Wins in past 10 race days')),
                ('avg_JKC_past_10', models.FloatField(help_text='Avg. JKC points in Past 10 race days')),
                ('number_win', models.IntegerField(help_text='No. of Wins')),
                ('number_second', models.IntegerField(help_text='No. of 2nds')),
                ('number_third', models.IntegerField(help_text='No. of 3rds')),
                ('number_fourth', models.IntegerField(help_text='No. of 4ths')),
                ('total_rides', models.IntegerField(help_text='Total Rides')),
                ('win_rate', models.FloatField(help_text='Win %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jockey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Jockey_Info', to='HKJC_database.Jockey_Info')),
            ],
            options={
                'ordering': ['number_win'],
            },
        ),
    ]
