# Generated by Django 3.0.3 on 2020-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0002_jockey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racingcourse',
            name='home_straight_M',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
