# Generated by Django 3.0.3 on 2020-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0002_auto_20200423_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse_info',
            name='dam_sire',
            field=models.CharField(blank=True, help_text="Enter the horse's dam_sire", max_length=100),
        ),
    ]
