# Generated by Django 3.0.3 on 2020-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0003_auto_20200422_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racingcourse',
            name='home_straight_M',
            field=models.FloatField(help_text='Enter the Home Straight(M)'),
        ),
        migrations.AlterField(
            model_name='racingcourse',
            name='width_M',
            field=models.FloatField(help_text='Enter the Width(M)'),
        ),
    ]
