# Generated by Django 3.0.3 on 2020-04-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0003_auto_20200423_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horse_info',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='horse_ranking',
            options={'ordering': ['horse']},
        ),
        migrations.AlterModelOptions(
            name='horse_report',
            options={'ordering': ['horse']},
        ),
        migrations.RemoveField(
            model_name='going',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='horse_info',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='jockey_info',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='racingcourse',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='trainer_info',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='horse_ranking',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horse_ranking_horse', to='HKJC_database.Horse_Info'),
        ),
        migrations.AlterField(
            model_name='horse_report',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horse_info_horse', to='HKJC_database.Horse_Info'),
        ),
    ]
