# Generated by Django 3.0.3 on 2020-04-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0004_auto_20200422_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jockey',
        ),
    ]
