# Generated by Django 3.0.3 on 2020-04-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0004_auto_20200423_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse_ranking',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='horse_report',
            name='horse',
        ),
        migrations.DeleteModel(
            name='Horse_info',
        ),
        migrations.DeleteModel(
            name='Horse_ranking',
        ),
        migrations.DeleteModel(
            name='Horse_Report',
        ),
    ]
