# Generated by Django 3.0.3 on 2020-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0005_delete_jockey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the jockey's name", max_length=50)),
                ('chinese_name', models.CharField(blank=True, help_text="Enter the jockey's chinese name", max_length=50)),
                ('hkjc_id', models.CharField(help_text="Enter the jockey's hkjc id", max_length=10)),
                ('stakes_won', models.FloatField(help_text='Enter the stakes Stakes won')),
                ('wins_past_10_racing', models.PositiveSmallIntegerField(help_text='Enter the No. of Wins in past 10 race days')),
                ('avg_JKC_past_10', models.FloatField(help_text='Avg. JKC points in Past 10 race days')),
                ('number_win', models.IntegerField(help_text='No. of Wins')),
                ('number_second', models.IntegerField(help_text='No. of 2nds')),
                ('number_third', models.IntegerField(help_text='No. of 3rds')),
                ('number_fourth', models.IntegerField(help_text='No. of 4ths')),
                ('total_rides', models.IntegerField(help_text='Total Rides')),
                ('win_rate', models.FloatField(help_text='Win %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number_win'],
            },
        ),
    ]
