# Generated by Django 3.0.3 on 2020-04-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0007_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jockey',
        ),
    ]
