# Generated by Django 3.0.3 on 2020-04-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0009_auto_20200423_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jockey_report',
            name='jockey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Jockey_Info', to='HKJC_database.Jockey_Info'),
        ),
    ]
