# Generated by Django 3.0.3 on 2020-04-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0011_match_info_match_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match_info',
            options={'ordering': ['match_date', 'race_number']},
        ),
        migrations.AddField(
            model_name='match_result',
            name='draw',
            field=models.IntegerField(blank=True, help_text='Enter draw of the horse', null=True),
        ),
    ]
