# Generated by Django 3.0.3 on 2020-04-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKJC_database', '0011_trainer_info_trainer_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_report',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trainer_Info', to='HKJC_database.Trainer_Info'),
        ),
    ]
